### ISSUE TITLE
Does pingernos actually use the prefix in the config.json?

### ISSUE THREAD

**Issue by Soapy7261** [PsychOps/serverpinger#29]
By looking at the code, it seems its hard coded and does not actually use the config.json, is it used somewhere else?
![Screenshot 2023-01-28 174622](https://user-images.githubusercontent.com/81933267/215294544-494c3daf-03f1-4d8b-84ad-77fdae8cccc6.png)
![Screenshot 2023-01-28 174640](https://user-images.githubusercontent.com/81933267/215294546-a0a97a26-22b3-4824-8b93-585c80176662.png)

**Comment by JoshuaSlui** [comment]
We use the one in the index.js because RegEXP failed to work in JSON (obviously)

**Comment by Soapy7261** [comment]
On an unrelated note, what does pingernos use the `guild_message_reactions` intent for? i mean receiving reactions kinda seems unneeded for what pingernos does
![Screenshot 2023-01-28 180507](https://user-images.githubusercontent.com/81933267/215295170-408c887d-bb5d-44c7-a56d-4406e2887c02.png)
Asking this because of the py-cord version im making

**Comment by JoshuaSlui** [comment]
We don't use it (anymore)

**Comment by Soapy7261** [comment]
Ah, alright good to know
