### ISSUE TITLE
[Bug?] Remove CodeQL

### ISSUE THREAD

**Issue by Soapy7261** [PsychOps/serverpinger#66]
Not even sure how it still exists since the file is gone in the workflows, but there has to be some way, right?

**Comment by JoshuaSlui** [comment]
When removing CodeQL, Github never removed CodeQL from the branch rules status checks configuration.
I've removed it and it should no longer show up for any future pull requests.

**Comment by Soapy7261** [comment]
🙏

**Comment by JoshuaSlui** [comment]
CodeQL still persisted, as Github apparently no longer stops CodeQL when the workflow file is removed,which means removing the branch rules had no actual effect. I've now properly killed it from our configurations.
